services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FEGA_SCHEMA_DIR=${FEGA_SCHEMA_DIR}
    ports:
      - "8082:80"
    env_file:
      - .env.local
    volumes:
      - ./logs:/usr/local/log
      - .:/api
    depends_on:
      - db
  db:
    image: postgres:16.3
    ports:
      - "5433:5432"
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  mailhog:
      image: mailhog/mailhog
      restart: always
      ports:
        - 1025:1025
        - 8025:8025
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
     - "5672:5672"
     - "15672:15672"

volumes:
  db-data:
    name: fega-db-data

