ServerName localhost

<VirtualHost *:80>
    ServerName api.fega.test
    DocumentRoot /api/public
    <Directory /api/public>
        Require all granted
        AllowOverride All
        FallbackResource /index.php
    </Directory>
</VirtualHost>