<?php

namespace App\Service\File;

use Exception;
use MeekroDB;
use PhpOffice\PhpSpreadsheet\IOFactory;

class FileImportHelper
{
    private MeekroDB $db;

    public function __construct(MeekroDB $db)
    {
        $this->db = $db;
    }

    public function convertXlsxToTsv(string $inputFileName, string $resourceType): string
    {
        if (!file_exists($inputFileName) || !is_readable($inputFileName)) {
            throw new Exception("Error: File '{$inputFileName}' cannot be read", 500);
        }

        $json = $this->db->queryFirstField("SELECT properties FROM resource_type WHERE name = %s", $resourceType);
        if (!$json) {
            throw new Exception("Unknown schemas for resource type '{$resourceType}'", 500);
        }

        $schemas = json_decode($json, true);

        // Get required fields from the table schema if available, otherwise fall back to the resource schema
        $required = [];
        if (isset($schemas['data_schema']['x-resource']['schema']['fields'])) {
            foreach ($schemas['data_schema']['x-resource']['schema']['fields'] as $field) {
                if (isset($field['constraints']['required']) && $field['constraints']['required']) {
                    $required[] = $field['name'];
                }
            }
        }

        if (empty($required)) {
            $required = $schemas['data_schema']['required'] ?? [];
        }

        $tsvFileName = dirname($inputFileName) . '/' . str_replace([".xlsx", ".xls"], ".tsv", basename($inputFileName));

        $filePointer = fopen($tsvFileName, 'w');
        if (!$filePointer) {
            throw new Exception("Cannot open file '{$tsvFileName}' for writing", 500);
        }

        $spreadsheet = IOFactory::load($inputFileName);
        $sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, false);

        $headerRowIndex = -1;
        $headers = [];

        foreach ($sheetData as $rowIndex => $cols) {
            // Skip empty first column rows
            if (empty($cols[0])) {
                continue;
            }

            if ($headerRowIndex === -1) {
                // Identify header row by matching required fields
                $checks = array_fill_keys($required, false);

                foreach ($cols as $col) {
                    if (array_key_exists($col, $checks)) {
                        $checks[$col] = true;
                    }
                }

                // Check if all required headers found
                if (!in_array(false, $checks, true)) {
                    $headerRowIndex = $rowIndex;
                    $headers = $cols;
                    // Write headers to TSV
                    fputcsv($filePointer, $cols, "\t", '"', '');
                }
            }
            elseif ($rowIndex === ($headerRowIndex + 1) && in_array($cols[0], ['string', 'from list', 'rename title'], true)) {
                // Skip row immediately after header if it contains formatting info
                continue;
            }
            elseif (count($headers) === count($cols)) {
                // Write valid data rows to TSV using tab delimiter, quoting disabled
                fputcsv($filePointer, $cols, "\t", '"', '');
            }
        }

        fclose($filePointer);

        if ($headerRowIndex === -1) {
            throw new Exception("Error: Could not find header row. Check template format.", 500);
        }

        if (!file_exists($tsvFileName)) {
            throw new Exception("Error: Unable to convert to TSV file", 500);
        }

        return $tsvFileName;
    }

    /**
     * Convert JSON data to TSV format
     */
    public function convertJsonDataToTsv(string $jsonFilePath, string $resourceType): string
    {
        // Read JSON data
        $jsonContent = file_get_contents($jsonFilePath);
        if ($jsonContent === false) {
            throw new Exception("Error: unable to read JSON file: {$jsonFilePath}", 500);
        }

        $data = json_decode($jsonContent, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new Exception("Error: invalid JSON data: " . json_last_error_msg(), 500);
        }

        // Get the resource type schema to determine field order
        $json_schemas = $this->db->queryFirstField("SELECT properties from resource_type where name = %s", $resourceType);
        if (!$json_schemas) {
            throw new Exception("Unknown resource type schema: {$resourceType}", 500);
        }

        $schemas = json_decode($json_schemas, true);
        if (!isset($schemas['data_schema']['properties'])) {
            throw new Exception("Unknown data_schema properties", 500);
        }

        // Fields that are auto-generated and should be excluded if not provided
        $autoGeneratedFields = ['public_id', 'id'];

        // Get field names in schema order, but only include fields that are either
        // present in the data or required by the schema (and not auto-generated)
        $schemaProperties = $schemas['data_schema']['properties'];
        $requiredFields = $schemas['data_schema']['required'] ?? [];

        $fieldNames = [];
        foreach (array_keys($schemaProperties) as $fieldName) {
            if (isset($data[$fieldName]) || (in_array($fieldName, $requiredFields) && !in_array($fieldName, $autoGeneratedFields))) {
                $fieldNames[] = $fieldName;
            }
        }

        // Create a TSV file
        $tsvFilePath = str_replace('.json', '.tsv', $jsonFilePath);
        $fp = fopen($tsvFilePath, 'w');
        if ($fp === false) {
            throw new Exception("Error: unable to create TSV file: {$tsvFilePath}", 500);
        }

        // Write a header row
        fputcsv($fp, $fieldNames, "\t", '"', '');

        // Write a data row
        $row = [];
        foreach ($fieldNames as $fieldName) {
            if (isset($data[$fieldName])) {
                $value = $data[$fieldName];
                // Convert arrays to semicolon-separated strings
                if (is_array($value)) {
                    $value = implode(';', $value);
                }
                $row[] = $value;
            }
            else {
                $row[] = ''; // Empty value for missing fields
            }
        }
        fputcsv($fp, $row, "\t", '"', '');

        fclose($fp);


        if (!file_exists($tsvFilePath)) {
            throw new Exception("Error: TSV file was not created: {$tsvFilePath}", 500);
        }

        return $tsvFilePath;
    }

    /**
     * Parse TSV or JSON into resource data arrays.
     */
    public function parseTsvOrJson(string $filePath, string $format): array
    {
        if ($format === 'json') {
            $data = json_decode(file_get_contents($filePath), true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                throw new Exception('Invalid JSON: ' . json_last_error_msg(), 400);
            }
            return [$data];
        }

        $handle = fopen($filePath, 'r');
        if (!$handle) {
            throw new Exception("Cannot read file: {$filePath}");
        }

        $headers = fgetcsv($handle, 0, "\t", "\"", "\\");
        $resourceData = [];
        while (($row = fgetcsv($handle, 0, "\t", "\"", "\\")) !== false) {
            $resource = [];
            foreach ($headers as $index => $header) {
                if (isset($row[$index]) && $row[$index] !== '') {
                    $value = $row[$index];
                    $resource[$header] = str_contains($value, ';') ? explode(';', $value) : $value;
                }
            }
            if (!empty($resource)) {
                $resourceData[] = $resource;
            }
        }
        fclose($handle);

        return $resourceData;
    }

    public function handleFilenameCollision(mixed $file, string $destination): array
    {
        $originalName = $file->getClientOriginalName();
        $pathInfo = pathinfo($originalName);
        $basename = $pathInfo['filename'];
        $ext = $pathInfo['extension'];

        $filename = $originalName;
        $numbers = [];

        if (file_exists($destination . $filename)) {
            $found = false;
            $nmd5 = md5_file($file->getRealPath());

            $pattern = "$basename*.$ext";
            $matches = glob($destination . $pattern);

            if (count($matches)) {
                foreach ($matches as $efile) {
                    if ($found) {
                        break;
                    }

                    $ebasename = pathinfo($efile, PATHINFO_BASENAME);
                    $emd5 = md5_file($efile);

                    if ($emd5 === $nmd5) {
                        $filename = $ebasename;
                        $found = true;
                    }
                    elseif (count($matches) === 1) {
                        $filename = "$basename.1.$ext";
                        $found = true;
                    }
                    else {
                        preg_match("/$basename\.(\d+)\.$ext/", $ebasename, $matchesNum);
                        if ($matchesNum) {
                            $numbers[] = (int)$matchesNum[1];
                        }
                    }
                }

                if (!$found && count($numbers)) {
                    $max = max($numbers);
                    $filename = "$basename." . ($max + 1) . ".$ext";
                }
            }
        }

        return ['filename' => $filename, 'original_name' => $originalName];
    }
}