#!/usr/bin/env bash
# =============================================================================
# db_restore.sh — FEGA database restore script
#
# Restores an FEGA database from a dump generated by db_dump.sh.
# The dump is user-agnostic (no OWNER / GRANT statements), so objects will
# be owned by whichever user performs the restore.
#
# Restore strategy (safe for repeated runs):
#   1. Drop the public schema and all its objects (CASCADE).
#   2. Recreate an empty public schema.
#   3. Apply the dump (schema + reference data).
#
# Usage:
#   ./db_restore.sh [OPTIONS] DUMP_FILE
#
# Options (all optional — fall back to env vars, then built-in defaults):
#   -e ENV_FILE    Load variables from a .env-style file
#   -h HOST        DB host          (default: $PGHOST / POSTGRES_HOST or localhost)
#   -p PORT        DB port          (default: $PGPORT / POSTGRES_PORT or 5432)
#   -d DATABASE    DB name          (default: $PGDATABASE / POSTGRES_DB, required)
#   -U USER        DB user          (default: $PGUSER / POSTGRES_USER)
#   -y             Skip confirmation prompt (non-interactive / CI mode)
#   --help         Show this help
#
# Examples:
#   # Interactive restore with prompt:
#   ./db_restore.sh -e .env.local -d fega-portal-dev fega_20260131_1245.sql
#
#   # Non-interactive (CI / scripted):
#   ./db_restore.sh -e tools/sync.env -y ./dumps/fega_20260131_1245.sql
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
usage() {
    sed -n '/^# Usage:/,/^# =/p' "$0" | sed 's/^# \?//'
    exit 0
}

die()  { echo "ERROR: $*" >&2; exit 1; }
log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
warn() { echo "WARNING: $*" >&2; }

# ---------------------------------------------------------------------------
# Argument parsing — pass 1: locate -e so the env file is loaded first
# ---------------------------------------------------------------------------
ENV_FILE=""
for ((i=1; i<=$#; i++)); do
    if [[ "${!i}" == "-e" ]]; then
        j=$((i+1))
        ENV_FILE="${!j}"
        break
    fi
done

if [[ -n "$ENV_FILE" ]]; then
    [[ -f "$ENV_FILE" ]] || die "Env file not found: $ENV_FILE"
    log "Loading env file: $ENV_FILE"
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
fi

# Map POSTGRES_* aliases → PG* so standard pg tools pick them up.
export PGHOST="${PGHOST:-${POSTGRES_HOST:-localhost}}"
export PGPORT="${PGPORT:-${POSTGRES_PORT:-5432}}"
export PGDATABASE="${PGDATABASE:-${POSTGRES_DB:-}}"
export PGUSER="${PGUSER:-${POSTGRES_USER:-}}"
export PGPASSWORD="${PGPASSWORD:-${POSTGRES_PASSWORD:-}}"

# ---------------------------------------------------------------------------
# Argument parsing — pass 2: all flags (override env / env-file values)
# ---------------------------------------------------------------------------
DB_HOST="$PGHOST"
DB_PORT="$PGPORT"
DB_NAME="$PGDATABASE"
DB_USER="$PGUSER"
DUMP_FILE=""
SKIP_CONFIRM=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        -e) shift 2 ;;
        -h) DB_HOST="$2"; shift 2 ;;
        -p) DB_PORT="$2"; shift 2 ;;
        -d) DB_NAME="$2"; shift 2 ;;
        -U) DB_USER="$2"; shift 2 ;;
        -y) SKIP_CONFIRM=true; shift ;;
        --help) usage ;;
        -*) die "Unknown option: $1. Use --help for usage." ;;
        *)
            [[ -n "$DUMP_FILE" ]] && die "Only one dump file may be specified."
            DUMP_FILE="$1"
            shift
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Validate inputs
# ---------------------------------------------------------------------------
[[ -z "$DB_NAME" ]]   && die "Database name is required. Use -d DATABASE or set PGDATABASE / POSTGRES_DB."
[[ -z "$DUMP_FILE" ]] && die "Dump file is required. Usage: $0 [OPTIONS] DUMP_FILE"
[[ -f "$DUMP_FILE" ]] || die "Dump file not found: $DUMP_FILE"

# ---------------------------------------------------------------------------
# Build connection arguments
# ---------------------------------------------------------------------------
PG_CONN_ARGS=(-h "$DB_HOST" -p "$DB_PORT")
[[ -n "$DB_USER" ]] && PG_CONN_ARGS+=(-U "$DB_USER")

# ---------------------------------------------------------------------------
# Verify connectivity
# ---------------------------------------------------------------------------
log "Checking connection to $DB_HOST:$DB_PORT/$DB_NAME …"
if ! PGPASSWORD="${PGPASSWORD:-}" psql "${PG_CONN_ARGS[@]}" -d "$DB_NAME" -c '\q' 2>/dev/null; then
    die "Cannot connect to database '$DB_NAME' on $DB_HOST:$DB_PORT. " \
        "Check host, port, credentials and that the database exists."
fi
log "Connection OK."

# ---------------------------------------------------------------------------
# Confirmation prompt (skipped with -y)
# ---------------------------------------------------------------------------
if [[ "$SKIP_CONFIRM" == false ]]; then
    echo ""
    echo "  ┌─────────────────────────────────────────────────────────────┐"
    echo "  │  WARNING: This will DROP all objects in the public schema   │"
    echo "  │  of database '$DB_NAME' on $DB_HOST:$DB_PORT"
    printf  "  │  %-61s│\n" "and restore from: $(basename "$DUMP_FILE")"
    echo "  │  All existing data will be permanently lost.               │"
    echo "  └─────────────────────────────────────────────────────────────┘"
    echo ""
    read -r -p "  Type 'yes' to continue: " CONFIRM
    [[ "$CONFIRM" == "yes" ]] || { echo "Aborted."; exit 0; }
    echo ""
fi

DUMP_FILE_ABS="$(cd "$(dirname "$DUMP_FILE")" && pwd)/$(basename "$DUMP_FILE")"

# ---------------------------------------------------------------------------
# Step 1: Wipe the public schema
# ---------------------------------------------------------------------------
log "Step 1/2: Dropping and recreating public schema on '$DB_NAME' …"
psql "${PG_CONN_ARGS[@]}" -d "$DB_NAME" -v ON_ERROR_STOP=1 -c \
    'DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;'

# ---------------------------------------------------------------------------
# Step 2: Apply the dump
# ---------------------------------------------------------------------------
log "Step 2/2: Restoring from $DUMP_FILE_ABS …"

# psql with ON_ERROR_STOP=0 so that expected NOTICEs (e.g. "does not exist,
# skipping") do not abort the restore, but genuine errors are reported.
RESTORE_LOG=$(mktemp)
trap 'rm -f "$RESTORE_LOG"' EXIT

psql "${PG_CONN_ARGS[@]}" \
    -d "$DB_NAME" \
    -v ON_ERROR_STOP=0 \
    -f "$DUMP_FILE_ABS" \
    2>"$RESTORE_LOG" || true

# Report any actual ERROR lines
ERROR_LINES=$(grep -c ': ERROR:' "$RESTORE_LOG" || true)
if [[ "$ERROR_LINES" -gt 0 ]]; then
    echo ""
    warn "$ERROR_LINES error(s) encountered during restore:"
    grep ': ERROR:' "$RESTORE_LOG" | sed 's/^/  /'
    echo ""
    die "Restore completed with errors — review the output above."
else
    NOTICE_LINES=$(grep -c ': NOTICE:' "$RESTORE_LOG" || true)
    [[ "$NOTICE_LINES" -gt 0 ]] && \
        log "($NOTICE_LINES informational NOTICE(s) — not errors, ignored)"
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
log "Restore complete. Database '$DB_NAME' is ready."
